### ISSUE TITLE
[FRONT] Rutas Admin (Mazos)

### ISSUE THREAD

**Issue by EliasReuter** [mackhood/TACS-UTN-2021#31]
- Los input están disabled

    - No está implementado nada para registrarse ni recuperar la contraseña (tip: es mucho más importante poder registrarse que recuperar una pass, y esto último no está contemplado como story)

    - Si me logueo y aprieto F5 o a continuación voy a /, me deslogueo o se pierde el estado del user actual (para solucionar esto usen cookies y almacenen el token que devuelva el back)

  - Ruta de admin (gestionar mazos):

    - Si quiero modificar un mazo creado, el botón queda disabled hasta tocar el input del nombre

    - En general la UI se pone inconsistente a la hora de handlear creación y modificación de mazos en el mismo lugar. Yendo un poco al código, veo que tienen un estado bool creating que podrían quitar si separan la lógica de crear y modificar en 2 pantallas distintas. Para esto pueden apoyarse en rutas de front diferentes (tip: .../decks/new y .../decks/edit/:deckId), o incluso modales simples que los ayuden a dividir la lógica y bajar bastante la complejidad del estado que guardan en el front. Más adelante en la corrección hablamos de handlear estado

    - Es posible crear dos mazos con el mismo nombre. Evalúen si esto es algo que quieren permitir o no (aunque pueden chequearlo en el front para una mejor UX, siempre se debe validar input del lado del servidor)

    - Nice to have: si bien la UI para el ABM está simple, y además está bueno el TransferList que usaron y se entiende bien, podrían aprovechar que se obtienen todos los datos de las cards para armar algo más visual que arme mazos, y para mostrarlos. Si quieren divertirse con eso, pueden adaptar ejemplos como este: https://www.youtube.com/watch?v=29deL9MFfWc

**Comment by GastiV** [comment]
Solucionados la mayoría y los que no se creó un issue por separado.

**Comment by GastiV** [comment]
"Nice to have: si bien la UI para el ABM está simple, y además está bueno el TransferList que usaron y se entiende bien, podrían aprovechar que se obtienen todos los datos de las cards para armar algo más visual que arme mazos, y para mostrarlos. Si quieren divertirse con eso, pueden adaptar ejemplos como este..."

Agregamos una visualización del mazo y vista previa del mazo cuando se está creando

**Comment by GastiV** [comment]
Si quiero modificar un mazo creado, el botón queda disabled hasta tocar el input del nombre

Arreglado en #53

**Comment by GastiV** [comment]
No está implementado nada para registrarse ni recuperar la contraseña (tip: es mucho más importante poder registrarse que recuperar una pass, y esto último no está contemplado como story)

Arreglado en #55

**Comment by GastiV** [comment]
"En general la UI se pone inconsistente a la hora de handlear creación y modificación de mazos en el mismo lugar. Yendo un poco al código, veo que tienen un estado bool creating que podrían quitar si separan la lógica de crear y modificar en 2 pantallas distintas. Para esto pueden apoyarse en rutas de front diferentes (tip: .../decks/new y .../decks/edit/:deckId), o incluso modales simples que los ayuden a dividir la lógica y bajar bastante la complejidad del estado que guardan en el front. Más adelante en la corrección hablamos de handlear estado"

Arreglado en #53
