### ISSUE TITLE
[FRONT] Manejo de estados

### ISSUE THREAD

**Issue by EliasReuter** [mackhood/TACS-UTN-2021#35]
manejar estado en las webapp react es un tema que se complejiza rápido si no se toman decisiones de antemano. Hay algunas cuestiones que está bueno evaluar:

  - Cuando tengo muchas pantallas con un montón de estado, qué hago? Por cómo está hecho react, se va generando un árbol de estado donde este se va pasando de a partes a componentes hijos en sus props (props = parámetros)

Lo más primitivo en react con hooks es hacer prop drilling + el hook de useState, que me deja almacenar algo de estado en cierto componente e ir pasándolo hacia abajo n niveles. Esto se puede poner feo rápido si tengo muchos niveles hacia abajo y reutilizo estado en varias partes del árbol

Existe otro hook parecido llamado useReducer, que permite armar un objeto {...} donde sus claves son el estado que se quiere almacenar (imaginen un useState = una clave del objetito del useReducer), y permite que le “mergeemos” actualizaciones al objeto de forma inmutable a través de funciones sencillas que se meten en un switch; si leen el ejemplito del tuto de react, estas actualizaciones son transparentes para la vista, y desde el punto de vista de la vista (valga la redundancia) es imposible mutar el objeto, haciendo a priori que sea consistente en todo momento. Si observan, todo esto lo están haciendo a mano y con efecto en Administration.js

En realidad useReducer es una mini implementación del patrón flux, que permite que una vista actualice estado de forma inmutable y unidireccional. Al objetito le dicen store, al switch le dicen reducer, y a lo que puede actualizar la vista se lo exponen con actions. De este patrón hay muchas implementaciones (rematch, redux, etc) y es una decisión a tomar si queremos incorporarlo al proyecto, y qué implementación elegir si lo hacemos (podemos comernos bastante boilerplate y overhead en implementarlo si elegimos implementaciones complejas como redux)

    - Cómo hago con las requests al back?

A veces en los updates a un estado se necesita hacer efecto de lado (ej: traer algo con un GET). Para solucionar esto existen varias formas, pero básicamente es lo que hicieron ustedes un poco más desacoplado. Lo que usen va a depender de la implementación, por eso está bueno ver cómo hace cada una para hacer efecto o hacer requests async (useReducer, rematch, redux-thunk). Prioricen lo simple, que cumpla

**Comment by GastiV** [comment]
Solucionado en #53
