### ISSUE TITLE
[FRONT] Issues sobre ProvideAuth.js

### ISSUE THREAD

**Issue by EliasReuter** [mackhood/TACS-UTN-2021#40]

**Comment by EliasReuter** [comment]
en signout tienen un setTimeout(() => {}, 400). Si bien puede que esto sea un stub de otra cosa, está bueno recordar que JS es un lenguaje async y que no sirve hacer eso como wait o sleep. Ese setTimeout va a correr una función vacía en 400ms sin bloquear nada, el código de debajo se ejecuta sin espera

**Comment by GastiV** [comment]
Por ahora el logout queda con un timeout fake.
cab5e909b0ad54707d247a50003bd0c17eb1b6f5
