### ISSUE TITLE
[FRONT] Issues sobre App.css

### ISSUE THREAD

**Issue by EliasReuter** [mackhood/TACS-UTN-2021#41]

**Comment by EliasReuter** [comment]
borren el boilerplate de create-react-app

**Comment by GastiV** [comment]
@Resuleto en #d753dbc947dda6ccb16a9385f657e2459d9b7f7b

**Comment by GastiV** [comment]
Resuleto en https://github.com/mackhood/TACS-UTN-2021/commit/d753dbc947dda6ccb16a9385f657e2459d9b7f7b
